# Generated by Django 5.1.4 on 2025-01-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='share_stress_level',
            field=models.BooleanField(default=False),
        ),
    ]
