# Generated by Django 5.1.4 on 2025-01-04 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stress', '0002_customuser_share_stress_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='course',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='stress.course'),
        ),
    ]
