# Generated by Django 5.1.4 on 2025-01-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stress', '0006_test_created_at_test_due_date_test_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='users', to='stress.test'),
        ),
    ]
